// Generated by CoffeeScript 1.7.1
(function() {
  var $, ACT, ON, SEL, TTTags, defaultOpts, subst,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  $ = jQuery;

  ON = 'ttton';

  SEL = 'tttsel';

  ACT = 'tttact';

  subst = function(expr, map) {
    return expr.replace(/\#{([^{}]*)}/g, function(a, b) {
      var r, t;
      r = map[b];
      if ((t = typeof r) === 'string' || t === 'number') {
        return r;
      } else {
        return a;
      }
    });
  };

  defaultOpts = {
    placeholder: '',
    template: '<a class="tag">#{tag}</a>',
    className: 'label label-default',
    allowNew: true,
    source: function() {},
    onTagAdd: function() {},
    onTagRemove: function() {},
    onFocus: function() {},
    onBlur: function() {}
  };

  TTTags = (function() {
    function TTTags(opts) {
      this._onInputKeyUp = __bind(this._onInputKeyUp, this);
      this._onInputKeyDown = __bind(this._onInputKeyDown, this);
      this._onInputBlur = __bind(this._onInputBlur, this);
      this._onInputFocus = __bind(this._onInputFocus, this);
      this._onFocus = __bind(this._onFocus, this);
      this._onClick = __bind(this._onClick, this);
      this._onMouseDown = __bind(this._onMouseDown, this);
      this._maybeShowPlaceholder = __bind(this._maybeShowPlaceholder, this);
      this._doSelect = __bind(this._doSelect, this);
      this._listStep = __bind(this._listStep, this);
      this._suggest = __bind(this._suggest, this);
      this._buildListAndInput = __bind(this._buildListAndInput, this);
      this._trigger = __bind(this._trigger, this);
      this.destroy = __bind(this.destroy, this);
      this.isActive = __bind(this.isActive, this);
      this.tags = __bind(this.tags, this);
      this.add = __bind(this.add, this);
      this.inList = __bind(this.inList, this);
      this.has = __bind(this.has, this);
      this.removeLast = __bind(this.removeLast, this);
      this.remove = __bind(this.remove, this);
      this.focus = __bind(this.focus, this);
      this.source = __bind(this.source, this);
      $.extend(this, Backbone.Events);
      this.opts = $.extend({}, defaultOpts, opts);
      this.$el = this.opts.$el;
      this.$el.addClass('tttags');
      this.$el.on('click', this._onClick);
      this.$el.on('mousedown', this._onMouseDown);
      this.$el.on('focus', this._onFocus);
      if (this.opts.placeholder) {
        $('<span class="tttplaceholder">').text(this.opts.placeholder).appendTo(this.$el);
        this._maybeShowPlaceholder();
      }
      this.src = this.opts.source;
    }

    TTTags.prototype.source = function(source) {
      var tags, _ref;
      if ((_ref = this.$list) != null) {
        _ref.remove();
      }
      this.$list = null;
      this.src = source;
      if (this.isActive()) {
        this._buildListAndInput();
        this._suggest(this.$input.text());
      }
      if ((tags = this.tags()).length) {
        tags.forEach((function(_this) {
          return function(tag) {
            if (!_this.inList(tag)) {
              return _this.remove(tag);
            }
          };
        })(this));
        this._maybeShowPlaceholder();
      }
      return this;
    };

    TTTags.prototype.focus = function() {
      this._buildListAndInput();
      this.$input.attr('contenteditable', true);
      this.$input.focus();
      return this;
    };

    TTTags.prototype.remove = function(tag, opts) {
      var $el;
      opts = opts != null ? opts : {};
      $el = tag;
      if (!(tag instanceof $)) {
        $el = $('.tag', this.$el).filter(function() {
          return $(this).text() === tag;
        });
      }
      if ($el != null ? $el.length : void 0) {
        $el.remove();
        if (!opts.silent) {
          this._trigger('remove', 'onTagRemove', $el.text(), $el);
        }
      }
      return this;
    };

    TTTags.prototype.removeLast = function() {
      this.remove($('.tag', this.$el).last());
      return this;
    };

    TTTags.prototype.has = function(tag) {
      return ($('.tag', this.$el).filter(function() {
        return $(this).text() === tag;
      })).length > 0;
    };

    TTTags.prototype.inList = function(tag) {
      this._buildListAndInput();
      return ($('li', this.$list).filter(function() {
        return $(this).text() === tag;
      })).length > 0;
    };

    TTTags.prototype.add = function(tag, opts) {
      var $el, inList;
      opts = opts != null ? opts : {};
      if (this.has(tag)) {
        return this;
      }
      if (!(this.opts.allowNew || opts.force || (inList = this.inList(tag)))) {
        return this;
      }
      $el = $(subst(this.opts.template, {
        tag: tag
      }));
      if (this.opts.className) {
        $el.addClass(this.opts.className);
      }
      if (this.$inputwrap) {
        this.$inputwrap.before($el);
      } else {
        if ($('.tag', this.$el).last().after($el).length === 0) {
          this.$el.prepend($el);
        }
      }
      $el.after(' ');
      if (!opts.silent) {
        this._trigger('add', 'onTagAdd', tag, $el, !inList);
      }
      return this;
    };

    TTTags.prototype.tags = function(toSet) {
      if (typeof toSet === 'string') {
        toSet = [toSet];
      }
      if ($.isArray(toSet)) {
        this.tags().forEach((function(_this) {
          return function(tag) {
            return _this.remove(tag, {
              silent: true
            });
          };
        })(this));
        toSet.forEach((function(_this) {
          return function(tag) {
            return _this.add(tag, {
              force: true,
              silent: true
            });
          };
        })(this));
        this._maybeShowPlaceholder();
        return this;
      } else {
        return ($('.tag', this.$el).map(function() {
          return $(this).text();
        })).toArray();
      }
    };

    TTTags.prototype.isActive = function() {
      return this.$el.hasClass(ACT);
    };

    TTTags.prototype.destroy = function() {
      var _ref, _ref1, _ref2;
      if (this.$input) {
        this.$input.off();
      }
      if (this.$el) {
        this.$el.off();
      }
      if ((_ref = this.$input) != null) {
        _ref.remove();
      }
      this.$input = null;
      if ((_ref1 = this.$list) != null) {
        _ref1.remove();
      }
      this.$list = null;
      if ((_ref2 = this.$inputwrap) != null) {
        _ref2.remove();
      }
      this.$inputwrap = null;
      this.$el.data('tttags', null);
      return this.$el = null;
    };

    TTTags.prototype._trigger = function(event, callback, tag, el, isNew) {
      var cb, evt;
      evt = {
        type: event,
        tags: this.tags(),
        src: this
      };
      if (tag) {
        evt.tag = tag;
      }
      if (el) {
        evt.el = el;
      }
      if (typeof isNew === 'boolean') {
        evt.isNew = isNew;
      }
      this.trigger(event, evt);
      cb = this.opts[callback];
      if (typeof cb === 'function') {
        return cb(evt);
      }
    };

    TTTags.prototype._buildListAndInput = function() {
      var $ol, s;
      if (!this.$input) {
        this.$inputwrap = $('<span class="tttinputwrap">').appendTo(this.$el);
        this.$input = $('<span class="tttinput"/>').appendTo(this.$inputwrap);
        this.$input.on('focus', this._onInputFocus);
        this.$input.on('blur', this._onInputBlur);
        this.$input.on('keydown', this._onInputKeyDown);
        this.$input.on('keyup', this._onInputKeyUp);
      }
      if (this.$list) {
        return;
      }
      this.$list = $('<div class="tttaglist">').appendTo(this.$inputwrap);
      $ol = $('<ol>').appendTo(this.$list);
      s = typeof this.src === 'function' ? this.src() : [];
      if (!$.isArray(s)) {
        s = [];
      }
      return s.forEach((function(_this) {
        return function(tag) {
          return $('<li>').text(tag).appendTo($ol);
        };
      })(this));
    };

    TTTags.prototype._suggest = function(txt) {
      var $sel, ltxt, show;
      if (this.lastSuggest !== txt) {
        ltxt = txt.toLowerCase();
        $('li', this.$list).each((function(_this) {
          return function(_, el) {
            var $el;
            $el = $(el);
            return $el.toggleClass(ON, $el.text().toLowerCase().indexOf(ltxt) === 0);
          };
        })(this));
        this.lastSuggest = txt;
        $sel = $('li.' + SEL, this.$list);
        if (!$sel.hasClass(ON)) {
          $sel.removeClass(SEL);
        }
        show = txt.length > 0 && $('li.' + ON, this.$list).length > 0;
        return this.$list.toggleClass(ON, show);
      }
    };

    TTTags.prototype._listStep = function(ev, up) {
      var $sel, lh, ls, sh, st, tmp;
      if (!this.$list.hasClass(ON)) {
        return;
      }
      $sel = $('li.' + SEL, this.$list);
      if ($sel.length) {
        if (up && (tmp = $sel.prevAll('li.' + ON)).length) {
          $sel.removeClass(SEL);
          tmp.first().addClass(SEL);
          ev.preventDefault();
        }
        if (!up && (tmp = $sel.nextAll('li.' + ON)).length) {
          $sel.removeClass(SEL);
          tmp.first().addClass(SEL);
          ev.preventDefault();
        }
      } else {
        if (up) {
          $('li.' + ON, this.$list).last().addClass(SEL);
          ev.preventDefault();
        } else {
          $('li.' + ON, this.$list).first().addClass(SEL);
          ev.preventDefault();
        }
      }
      $sel = $('li.' + SEL, this.$list);
      if ($sel.length === 0) {
        return;
      }
      lh = this.$list.outerHeight();
      ls = this.$list.scrollTop();
      st = $sel[0].offsetTop;
      sh = $sel.outerHeight();
      if ((st + sh) > (lh + ls)) {
        this.$list.scrollTop((st + sh) - lh);
      }
      if (st < ls) {
        return this.$list.scrollTop(st);
      }
    };

    TTTags.prototype._doSelect = function() {
      var $sel;
      $sel = $('li.' + SEL, this.$list);
      if ($sel.length) {
        this.add($sel.text(), {
          force: true
        });
      } else {
        this.add(this.$input.text(), {
          force: false
        });
      }
      this.$input.text('');
      return this._suggest('');
    };

    TTTags.prototype._maybeShowPlaceholder = function() {
      return $('.tttplaceholder', this.$el).toggleClass(ON, $('.tag', this.$el).length === 0);
    };

    TTTags.prototype._onMouseDown = function(ev) {
      var $t, li;
      $t = $(ev.target);
      if ((li = $t.closest('li')).length > 0) {
        $('li.' + SEL, this.$list).removeClass(SEL);
        li.addClass(SEL);
        this._doSelect();
      }
      if (this.isActive()) {
        return ev.preventDefault();
      }
    };

    TTTags.prototype._onClick = function(ev) {
      var $t;
      $t = $(ev.target);
      return this.focus();
    };

    TTTags.prototype._onFocus = function(ev) {
      return this.focus();
    };

    TTTags.prototype._onInputFocus = function(ev) {
      if (this.isActive()) {
        return;
      }
      this.$el.addClass(ACT);
      return this._trigger('focus', 'onFocus');
    };

    TTTags.prototype._onInputBlur = function(ev) {
      if (!this.isActive()) {
        return;
      }
      this.$el.removeClass(ACT);
      this.$input.text('').removeAttr('contenteditable');
      this._suggest('');
      $('li.' + SEL, this.$list).removeClass(SEL);
      this._maybeShowPlaceholder();
      return this._trigger('blur', 'onBlur');
    };

    TTTags.prototype._onInputKeyDown = function(ev) {
      var range, _ref;
      switch (ev.keyCode) {
        case 13:
          ev.preventDefault();
          return this._doSelect();
        case 27:
          return this.$input.blur();
        case 8:
          range = typeof window !== "undefined" && window !== null ? window.getSelection().getRangeAt(0) : void 0;
          if (range) {
            if ((range.startOffset === (_ref = range.endOffset) && _ref === 0)) {
              return this.removeLast();
            }
          } else {
            if (this.$input.text() === '') {
              return this.removeLast();
            }
          }
          break;
        case 38:
          return this._listStep(ev, true);
        case 40:
          return this._listStep(ev, false);
      }
    };

    TTTags.prototype._onInputKeyUp = function(ev) {
      return this._suggest(this.$input.text());
    };

    return TTTags;

  })();

  $.fn.tttags = function(action, data) {
    var obj, opts;
    opts = null;
    if ($.isPlainObject(action)) {
      opts = action;
      action = null;
    }
    obj = null;
    this.each(function(i, el) {
      var $el, topts;
      $el = $(el);
      obj = $el.data('tttags');
      if (!obj) {
        topts = $.extend({}, opts);
        topts.$el = $el;
        $el.data('tttags', obj = new TTTags(topts));
      }
      if (action) {
        return obj[action](data);
      }
    });
    if (action || opts) {
      return this;
    } else {
      return obj;
    }
  };

}).call(this);
